name: Serial-workflow
on: workflow_dispatch
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps: 
      - name: building-steps
        run: echo "building jobs"
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: testing-step
        run: echo "testing jobs"
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-step
        run: echo "deploy jobs" 
